import { useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, ShieldCheck, UploadCloud } from 'lucide-react'

const heroImage = '/landing/aurum-hero-site.jpg'
const uploadFields: [string, string, boolean][] = [['drawings', 'Drawings', true], ['specification', 'Specification', false], ['boq', 'Bill of Quantities', false]]

export default function RequestQuotePage() {
  const [files, setFiles] = useState<Record<string, File[]>>({})
  const [busy, setBusy] = useState(false)
  const [done, setDone] = useState(false)
  const [error, setError] = useState('')
  const submit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault(); setBusy(true); setError('')
    const form = e.currentTarget
    const data = new FormData(form)
    Object.entries(files).forEach(([kind, list]) => list.forEach(f => data.append(kind, f)))
    try {
      const r = await fetch('/api/business/quote-requests', { method: 'POST', body: data })
      const j = await r.json()
      if (!r.ok) throw new Error(j.message || 'Submission failed')
      setDone(true); window.scrollTo({ top: 0, behavior: 'smooth' })
    } catch (err: any) { setError(err.message || 'Something went wrong.') } finally { setBusy(false) }
  }
  const filePicker = (kind: string) => (e: React.ChangeEvent<HTMLInputElement>) => setFiles(v => ({ ...v, [kind]: Array.from(e.target.files || []) }))

  if (done) return <div className="min-h-screen bg-[#f7f7f4] px-5 py-16"><div className="mx-auto max-w-xl rounded-3xl border border-black/[.06] bg-white p-8 text-center shadow-xl sm:p-12"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><CheckCircle2 size={32}/></div><p className="mt-7 text-[10px] font-extrabold uppercase tracking-[.22em] text-amber-700">Request received</p><h1 className="mt-3 font-display text-3xl font-semibold">Thanks for getting in touch.</h1><p className="mt-4 text-sm leading-7 text-slate-600">Your project information has been received. We’ll review the scope and come back with next steps, the proposed deliverables, programme and fixed fee.</p><Link to="/" className="mt-8 inline-flex items-center gap-2 rounded-lg bg-[#17211f] px-5 py-3 text-sm font-bold text-white">Back to Aurum <ArrowRight size={16}/></Link></div></div>

  return <div className="min-h-screen bg-[#f7f7f4] text-[#17211f]">
    <header className="border-b border-black/[.06] bg-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between px-5 py-4 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#17211f] font-display text-lg font-black text-amber-300">A</div><div><div className="text-sm font-extrabold tracking-[.15em]">AURUM</div><div className="text-[9px] uppercase tracking-[.22em] text-slate-400">Project Controls</div></div></Link><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold text-slate-500 transition hover:text-slate-900"><ArrowLeft size={15}/> Back to website</Link></div></header>
    <main className="mx-auto grid max-w-[1400px] gap-8 px-5 py-8 sm:px-8 sm:py-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-12 lg:px-10">
      <aside className="relative min-h-[360px] overflow-hidden rounded-3xl bg-[#101b19] text-white lg:sticky lg:top-8 lg:h-[680px]"><img src={heroImage} alt="Construction project" className="absolute inset-0 h-full w-full object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-t from-[#101b19] via-[#101b19]/65 to-[#101b19]/15"/><div className="relative flex h-full flex-col justify-between p-7 sm:p-9"><div><div className="inline-flex items-center gap-2 rounded-full border border-amber-300/30 bg-black/20 px-3 py-2 text-[9px] font-extrabold uppercase tracking-[.18em] text-amber-200"><ShieldCheck size={13}/> Private project submission</div><p className="mt-10 text-[10px] font-extrabold uppercase tracking-[.22em] text-amber-300">Start a conversation</p><h1 className="mt-3 max-w-lg font-display text-4xl font-semibold leading-tight tracking-[-.04em] sm:text-5xl">Tell us about your next tender.</h1><p className="mt-5 max-w-md text-sm leading-7 text-white/70">Send the project details and the documents you have available. We’ll review the scope before proposing a fee.</p></div><div><div className="mb-5 grid grid-cols-3 gap-2">{[['01','Your details'],['02','Project scope'],['03','Documents']].map(([n,t])=><div key={n} className="rounded-xl border border-white/15 bg-black/20 p-3"><div className="text-[10px] font-extrabold text-amber-300">{n}</div><div className="mt-1 text-[10px] font-semibold text-white/75">{t}</div></div>)}</div><p className="text-xs leading-5 text-white/55">You don’t need to have every document ready to start. Submit what you have and tell us what is still outstanding.</p></div></div></aside>
      <div><div className="mb-8"><p className="mb-3 text-[10px] font-extrabold uppercase tracking-[.22em] text-amber-700">Request a quotation</p><h2 className="font-display text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Project information</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-600">We’ll use this information to understand the job and prepare a clear proposal covering the scope, deliverables, programme and fixed fee.</p></div>
      <form onSubmit={submit} className="space-y-5">
        <section className="rounded-2xl border border-black/[.06] bg-white p-5 shadow-[0_8px_30px_rgba(18,31,27,.025)] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#17211f] text-amber-300"><FileText size={17}/></div><div><h3 className="font-display text-lg font-semibold">Your details</h3><p className="mt-0.5 text-xs text-slate-500">Who should we contact about this project?</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['name','Your name','text'],['company','Company','text'],['email','Work email','email'],['telephone','Telephone','tel'],['projectName','Project name','text'],['projectLocation','Project location','text']].map(([n,l,t])=><label key={n} className="block text-xs font-bold text-slate-700">{l}{['name','company','email','projectName'].includes(n)&&<span className="ml-1 text-amber-700">*</span>}<input name={n} type={t} required={['name','company','email','projectName'].includes(n)} placeholder={n==='projectLocation'?'Town / site location':''} className="mt-2 w-full rounded-lg border border-slate-200 bg-[#fbfbf9] px-3.5 py-3 text-sm font-normal outline-none transition placeholder:text-slate-300 focus:border-amber-500 focus:bg-white focus:ring-4 focus:ring-amber-500/10"/></label>)}</div></section>
        <section className="rounded-2xl border border-black/[.06] bg-white p-5 shadow-[0_8px_30px_rgba(18,31,27,.025)] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#17211f] text-amber-300"><CheckCircle2 size={17}/></div><div><h3 className="font-display text-lg font-semibold">Tender information</h3><p className="mt-0.5 text-xs text-slate-500">Help us understand what you need and when.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="block text-xs font-bold text-slate-700">Service required <span className="text-amber-700">*</span><select name="service" required className="mt-2 w-full rounded-lg border border-slate-200 bg-[#fbfbf9] px-3.5 py-3 text-sm font-normal outline-none focus:border-amber-500 focus:ring-4 focus:ring-amber-500/10"><option value="">Choose a service</option><option>Take-off</option><option>Estimate</option><option>Tender support</option><option>Commercial support</option><option>Bill of Quantities</option><option>Variation</option><option>Valuation</option><option>Other</option></select></label><label className="block text-xs font-bold text-slate-700">Tender deadline<input name="tenderDeadline" type="date" className="mt-2 w-full rounded-lg border border-slate-200 bg-[#fbfbf9] px-3.5 py-3 text-sm font-normal outline-none focus:border-amber-500 focus:ring-4 focus:ring-amber-500/10"/></label></div><label className="mt-5 block text-xs font-bold text-slate-700">Brief project description<textarea name="briefDescription" rows={5} placeholder="What needs measuring, estimating or supporting? Include any key trades, deadline or project requirements." className="mt-2 w-full resize-y rounded-lg border border-slate-200 bg-[#fbfbf9] px-3.5 py-3 text-sm font-normal leading-6 outline-none transition placeholder:text-slate-300 focus:border-amber-500 focus:bg-white focus:ring-4 focus:ring-amber-500/10"/></label></section>
        <section className="rounded-2xl border border-black/[.06] bg-white p-5 shadow-[0_8px_30px_rgba(18,31,27,.025)] sm:p-7"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#17211f] text-amber-300"><UploadCloud size={17}/></div><div><h3 className="font-display text-lg font-semibold">Project documents</h3><p className="mt-0.5 text-xs text-slate-500">Upload any drawings, specification or BoQ you have.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{uploadFields.map(([n,l,multi])=><label key={n} className="group cursor-pointer rounded-xl border border-dashed border-slate-300 bg-[#fbfbf9] p-4 transition hover:border-amber-500 hover:bg-amber-50/40"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-white text-slate-500 shadow-sm transition group-hover:text-amber-700"><UploadCloud size={17}/></div><div className="mt-3 text-xs font-extrabold">{l}</div><div className="mt-1 break-words text-[10px] leading-4 text-slate-500">{files[String(n)]?.length ? files[String(n)].map(f=>f.name).join(', ') : 'Click to choose file'}</div><input type="file" className="hidden" multiple={Boolean(multi)} onChange={filePicker(String(n))}/></label>)}</div><p className="mt-4 text-[10px] leading-5 text-slate-500">Maximum 25 MB per file. If you have multiple drawings, you can select them together in the drawings upload.</p></section>
        {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
        <div className="rounded-2xl bg-[#e9ece6] p-5 sm:flex sm:items-center sm:justify-between sm:gap-6 sm:p-6"><p className="text-[10px] leading-5 text-slate-600">By submitting, you confirm the information is supplied to help Aurum prepare a quotation for your project.</p><button disabled={busy} className="mt-4 inline-flex w-full shrink-0 items-center justify-center gap-2 rounded-lg bg-[#17211f] px-6 py-3.5 text-sm font-extrabold text-white transition hover:bg-[#263a34] disabled:cursor-wait disabled:opacity-50 sm:mt-0 sm:w-auto">{busy?'Submitting…':'Submit for review'} {busy ? null : <ArrowRight size={16}/>}</button></div>
      </form></div>
    </main>
    <footer className="border-t border-black/[.06] bg-white px-5 py-6 text-center text-[10px] text-slate-500">© {new Date().getFullYear()} Aurum Project Controls · <Link to="/legal/privacy" className="font-semibold hover:text-slate-900">Privacy notice</Link></footer>
  </div>
}
